[package]
name = "galois-bin"
version = "0.7.0-dev"
authors = ["UINB Technologies"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/uinb/galois"

[[bin]]
name = "galois"
path = "src/galois.rs"

[[bin]]
name = "sidecar"
path = "src/sidecar.rs"

[dependencies]
engine = { path = "../engine", package = "galois-engine" }
sidecar = { path = "../sidecar", package = "galois-sidecar" }
jsonrpsee = { version = "0.16.2", features = ["full"] }
tokio = { version = "1.16", features = ["full"] }
tower = "0.4.13"
clap = { version = "4.1.7", features = ["derive"] }
env_logger = "0.10"
lazy_static = "1.4"
log = { version = "0.4", features = ["serde"] }
anyhow =  "1"
