name: Rust CI 

on:
  push:
    branches: [ master, offchain ]
  pull_request:
    branches: [ master, offchain ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-12-22
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features "enc-conf"
