name: Release

on:
  push:
    tags: [ "v*" ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-release:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-01-29
          override: true
          components: rustfmt, clippy
      - name: Build release with all features enabled
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: montudor/action-zip@v1
        with:
          args: zip -j -r galois.zip target/release/galois target/release/sidecar galois.toml.example sidecar.toml.example README.md LICENSE
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: galois.zip
          tag: ${{ github.ref }}
          overwrite: true
